-- Script para adicionar apenas os campos de status na tabela IMPRESSORAS
-- Execute este script no SQL Server Management Studio

USE ImpressorasDB;
GO

-- Verificar se as colunas já existem antes de adicionar
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPRESSORAS' AND COLUMN_NAME = 'STATUS_REPARO')
BEGIN
    ALTER TABLE IMPRESSORAS ADD STATUS_REPARO VARCHAR(50) NULL;
    PRINT 'Coluna STATUS_REPARO adicionada com sucesso';
END
ELSE
BEGIN
    PRINT 'Coluna STATUS_REPARO já existe';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IMPRESSORAS' AND COLUMN_NAME = 'STATUS_SERVICO')
BEGIN
    ALTER TABLE IMPRESSORAS ADD STATUS_SERVICO VARCHAR(50) NULL;
    PRINT 'Coluna STATUS_SERVICO adicionada com sucesso';
END
ELSE
BEGIN
    PRINT 'Coluna STATUS_SERVICO já existe';
END

-- Verificar se as colunas foram criadas
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'IMPRESSORAS' 
AND COLUMN_NAME IN ('STATUS_REPARO', 'STATUS_SERVICO')
ORDER BY COLUMN_NAME;